import { jsPDF } from 'jspdf';
import 'jspdf-autotable';

export function generatePDF(reportData) {
  const doc = new jsPDF();
  
  // Header
  doc.setFontSize(22);
  doc.text('ReportReady Audit Report', 20, 20);
  
  doc.setFontSize(12);
  doc.text(`URL: ${reportData.url}`, 20, 30);
  doc.text(`Date: ${new Date(reportData.timestamp).toLocaleString()}`, 20, 37);
  
  // Scores
  doc.setFontSize(16);
  doc.text('Scores', 20, 50);
  
  const scoreData = Object.entries(reportData.scores).map(([key, value]) => [
    key.charAt(0).toUpperCase() + key.slice(1),
    value.toString()
  ]);
  
  doc.autoTable({
    startY: 55,
    head: [['Category', 'Score']],
    body: scoreData,
    theme: 'striped'
  });
  
  // Issues
  const finalY = doc.lastAutoTable.finalY || 100;
  doc.setFontSize(16);
  doc.text('Issues Identified', 20, finalY + 15);
  
  const issueData = reportData.issues.map(issue => [
    issue.category,
    issue.message,
    issue.severity
  ]);
  
  doc.autoTable({
    startY: finalY + 20,
    head: [['Category', 'Description', 'Severity']],
    body: issueData,
    theme: 'grid',
    headStyles: { fillColor: [170, 59, 255] }
  });
  
  // Footer
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(10);
    doc.text(`Page ${i} of ${pageCount} - Generated by ReportReady`, 20, 285);
  }
  
  return doc.output('arraybuffer');
}
